questions = {
    1 : "What is normalized data?",
    2 : 'Which option falls under normal forms?',
    3 : 'What does cardinality mean?',
    4 : 'What is referential integrity?',
    5 : 'What is a many-to-many relaionship?',
    6 : 'What is denormalized data?',
    7 : 'What is an example of NoSQL Document-oriented formats?',
    8 : 'What is a primary key?',
    9 : 'What is a relational database?',
    10 : 'Which option falls under NoSQL categories?',
    11 : 'What is a schema?',
    12 : 'How many normal forms are there total?',
    13 : 'What is structured query language (SQL)?',
    14 : 'What is cascade update?',
    15 : 'What is a one-to-many relationship?',
    16 : 'What are some examples of a RDBMS?',
    17 : 'What is a relational database mangaement system (RDBMS)?',
    18 : 'What type of database offers flexibility and scalability?',
    19 : 'What is a one-to-one relationship',
    20 : 'What is a non-relational database?',
    21 : 'What is a foreign key?',
    22 : 'What type of databse use primary and foreign keys?',
    23 : 'What are the four NoSQL database categories?',
    24 : 'What is cascade delete?',
    25 : 'Give an example of a key-value store database',
    26 : 'Give an example of a column-oriented database',
    27 : 'What is another name for a non-relational database?'
}